# Generated by Django 3.2.4 on 2021-06-26 18:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Sheep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identification_number', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('gender', models.CharField(choices=[('H', 'Hembra'), ('M', 'Macho')], max_length=1)),
                ('birthday', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('parentDadId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dad', to='myapp.sheep')),
                ('parentMomId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom', to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='SheepPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('upload', models.FileField(upload_to='media/')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='SheepBreed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.breed')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryWeight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
    ]
