# Generated by Django 3.2.4 on 2021-06-27 15:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryWeather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(choices=[('N', 'Nevera'), ('L', 'Laboratorio'), ('A', 'Aprisco')], max_length=1)),
            ],
        ),
    ]
