# Generated by Django 3.2.4 on 2021-07-05 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20210704_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheepbreed',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='myapp.breed'),
        ),
        migrations.AlterField(
            model_name='sheepbreed',
            name='sheep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breed', to='myapp.sheep'),
        ),
    ]
