# Generated by Django 3.2.4 on 2022-02-06 19:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210704_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Observations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryFamacha',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('famacha', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryBodyCondition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body_condition', models.DecimalField(decimal_places=2, max_digits=7)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
    ]
