# Generated by Django 3.2.4 on 2022-04-22 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_historypluviometer_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheep',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='identification_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='identification_number_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='parentDadId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dad', to='myapp.sheep'),
        ),
        migrations.AlterField(
            model_name='sheep',
            name='parentMomId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mom', to='myapp.sheep'),
        ),
    ]
