# Generated by Django 3.2.4 on 2022-04-28 13:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20220421_2150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('active', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='SheepGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheep', to='myapp.group')),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField()),
                ('sheep_hembra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_hembra', to='myapp.sheep')),
                ('sheep_macho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_macho', to='myapp.sheep')),
            ],
        ),
        migrations.CreateModel(
            name='HistorySheep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=500)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('sheep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.sheep')),
            ],
        ),
    ]
