# Generated by Django 3.2.4 on 2022-04-30 22:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_group_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historysheep',
            options={'ordering': ['-create_at']},
        ),
        migrations.AlterModelOptions(
            name='historyweight',
            options={'ordering': ['create_at']},
        ),
        migrations.AlterField(
            model_name='service',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='date_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='Mancha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_hembra', to='myapp.service')),
            ],
        ),
    ]
