# Generated by Django 3.2.4 on 2022-05-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_auto_20220430_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyweight',
            name='weight',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
