# Generated by Django 3.2.4 on 2022-05-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_historyweight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sheepgroup',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
