# Generated by Django 3.2.4 on 2022-05-01 23:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_alter_sheepgroup_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historybodycondition',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historyfamacha',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historyweight',
            name='create_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
